version: '2'
services:
  cloud9:
      image: 'egoexpress/cloud9'
      environment:
        - VIRTUAL_HOST=${c9_hostname}
        - CLOUD9_USER=${c9_user}
        - CLOUD9_PASS=${c9_password}
      volumes:
        - 'cloud9_data:/workspace'
      ports:
        - ${public_port}:80
volumes:
  cloud9_data:
    driver: ${volume_driver}