version: '2'
services:
  cloud9:
      image: 'kdelfour/cloud9-docker'
      environment:
        - VIRTUAL_HOST=${DOCKER_CLOUD9_HOSTNAME}
        - CLOUD9_USER=${DOCKER_CLOUD9_USERNAME}
        - CLOUD9_PASS=${DOCKER_CLOUD9_PASSWORD}
      volumes:
        - 'cloud9_data:/workspace'
      ports:
        - ${public_port}:80
volumes:
  cloud9_data:
    driver: ${volume_driver}